### ISSUE TITLE
Could not pass player quit to Skywars

### ISSUE THREAD

**Issue by Scott943** [SkyWars/SkyWars#154]
When a player quits it sometimes comes up with:
```
[17:59:48] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to SkyWars v2.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at net.minecraft.server.v1_7_R4.PlayerList.disconnect(PlayerList.java:321) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:738) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:77) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
Caused by: java.lang.NullPointerException
	at net.daboross.bukkitdev.skywars.player.OnlineSkyPlayers.unloadPlayer(OnlineSkyPlayers.java:102) ~[?:?]
	at net.daboross.bukkitdev.skywars.listeners.StorageLoadListener.onQuit(StorageLoadListener.java:40) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[Spigot-patched.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
	... 11 more
[17:59:48] [Server thread/INFO]: scottparker943 left the game.
```
Help please :)

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work. However, I believe this is fixed in v2.0.1.
