### ISSUE TITLE
Startup failed

### ISSUE THREAD

**Issue by riassmismans** [SkyWars/SkyWars#201]
#### Issue / Bug / Crash:

Server Version: 1.9 Spigot

Any errors in console?:

[17:33:12 INFO]: [SkyWars] Enabling SkyWars v2.1.1
[17:33:12 INFO]: [SkyWars] Setting config-version to 2 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting debug to false in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting skip-uuid-version-check to false in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting arena-order to RANDOM in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting message-prefix to &8[&cSkyWars&8]&a  in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting save-inventory to true in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting save-experience to true in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting save-position-gamemode-health to true in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting enabled-arenas to [skyblock-warriors, water-warriors] in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting locale to nl in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting skywars-arena-gamerules to {doDaylightCycle=false} in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.enable-points to true in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.win-point-diff to 7 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.death-point-diff to -2 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.kill-point-diff to 1 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.max-save-interval to 300 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.use-sql to false in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.sql.host to 127.0.0.1 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.sql.port to 3.306 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.sql.database to minecraft in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.sql.username to root in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting points.sql.password to aComplexPassword in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting economy.enable-economy to false in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting economy.kill-reward to 10 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting economy.win-reward to 10 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting economy.reward-messages to true in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting arena-distance-apart to 200 in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting command-whitelist.whitelist-enabled to true in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting command-whitelist.treated-as-blacklist to false in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting command-whitelist.whitelist to [/skywars, /sw, /me] in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting hooks.multiverse-core-hook to true in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting hooks.multiverse-inventories-hook to true in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] Setting hooks.worldedit-hook to true in file plugins\SkyWars\main-config.yml
[17:33:12 INFO]: [SkyWars] [Translations] Loading locale nl.
[17:33:12 INFO]: [SkyWars] Using WorldEdit hook for arena creation.
[17:33:12 ERROR]: [SkyWars] Startup failed
java.lang.NoClassDefFoundError: com/sk89q/worldedit/world/AbstractWorld
        at net.daboross.bukkitdev.skywars.world.SkyWorldHandler.<init>(SkyWorldHandler.java:59) ~[SkyWars%20(1).jar:skywars-2.1.1]
        at net.daboross.bukkitdev.skywars.SkyWarsPlugin.startPlugin(SkyWarsPlugin.java:149) ~[SkyWars%20(1).jar:skywars-2.1.1]
        at net.daboross.bukkitdev.skywars.SkyWarsPlugin.onEnable(SkyWarsPlugin.java:118) [SkyWars%20(1).jar:skywars-2.1.1]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.world.AbstractWorld
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_73]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-095e59a-a12b1a4]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
        ... 14 more
[17:33:12 INFO]: [SkyWars] Disabling SkyWars v2.1.1

**Comment by daboross** [comment]
This is probably due to an outdated WorldEdit version. I'll add a more duscriptive error for this, but the fix will be to update WorldEdit or disable the WorldEdit hook.

**Comment by riassmismans** [comment]
Thanks, I installed a new version of WorldEdit and now it works.

**Comment by daboross** [comment]
Awesome! Going to close this issue.
