### ISSUE TITLE
Saved inventory is null when two players die directly before game ends.

### ISSUE THREAD

**Issue by daboross** [SkyWars/SkyWars#205]
#### Issue / Bug / Crash:

Server Version: Minecraft 1.8.3, but nothing seems specific to that version

When did this issue occur?: Ending game

Output url from `/sw report`: https://gist.github.com/anonymous/254d609d0c110d3475b3

```
[20:41:20] [Server thread/INFO]: zbsh issued server command: /sw join
[20:41:24] [Server thread/INFO]: 1 issued server command: /sw join
[20:41:24] [Server thread/INFO]: 2 issued server command: /sw join
[20:41:24] [Server thread/INFO]: ESC[0;30;1m[ESC[0;31;1mSkyWarsESC[0;30;1m]ESC[0;32;1m ESC[0;32;1mGame starting with ESC[0;32;22m2ESC[0;32;1m, 
ESC[0;32;22m1ESC[0;32;1m and ESC[0;32;22mzbshESC[0;32;1m!ESC[m
[20:41:38] [Server thread/INFO]: [SkyWars] ZOMBIE killed 2!
[20:41:38] [Server thread/INFO]: 2 died
[20:41:42] [Server thread/INFO]: [SkyWars] zbsh jumped into the void of doom!
[20:41:42] [Server thread/INFO]: 1 died
[20:41:42] [Server thread/INFO]: Respawn event! location: Location{world=CraftWorld{name=world},x=-118.5,y=64.0,z=262.5,pitch=0.0,yaw=0.0} bed: 
false evt: org.bukkit.event.player.PlayerRespawnEvent@7a5130fb
[20:41:42] [Server thread/INFO]: ESC[0;30;1m[ESC[0;31;1mSkyWarsESC[0;30;1m]ESC[0;32;1m ESC[0;32;22m1ESC[0;32;1m has won the SkyWars!ESC[m
[20:41:43] [Server thread/ERROR]: [SkyWars] Couldn't broadcast PlayerRespawnAfterGameEnd in SkyWars version skywars-2.1.2-5-gfeaedd0 - 2.1.3-SNAPSHOT:
java.lang.IllegalArgumentException: Saved inventory for zbsh was null!
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.daboross.bukkitdev.skywars.events.listeners.InventorySaveListener.onPlayerRespawn(InventorySaveListener.java:63) ~[skywars.jar:skywars-2.1.2-5-gfeaedd0]
        at net.daboross.bukkitdev.skywars.events.GameEventDistributor.distribute(GameEventDistributor.java:129) [skywars.jar:skywars-2.1.2-5-gfeaedd0]
        at net.daboross.bukkitdev.skywars.game.GameHandler.respawnPlayer(GameHandler.java:149) [skywars.jar:skywars-2.1.2-5-gfeaedd0]
        at net.daboross.bukkitdev.skywars.listeners.AttackerStorageListener$2.run(AttackerStorageListener.java:190) [skywars.jar:skywars-2.1.2-5-gfeaedd0]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

**Comment by daboross** [comment]
Seems this was just an error in some work-in-progess code.
