### ISSUE TITLE
no skywarsmap are build

### ISSUE THREAD

**Issue by 011248163264** [SkyWars/SkyWars#272]
#### Issue / Bug / Crash:

Server Version: 1.12.2 Java 8 

When did this issue occur?: I have execude the /sws start <name>, no map in the sky 

What did you expect to happen?:
I have set a spawn and a join gold block (portal), after this i have seen the video
https://www.youtube.com/watch?v=c6EqmpGnF40 but i have no skywars in my map ?!

What happened?: no skywarsmap are build

Output url from `/sw report`: mc.doseplay.net

Any errors in console?: no

Its a great plugin but its not working, can any help me, what can i do ?

**Comment by 011248163264** [comment]
[20:36:54] [Server thread/INFO]: DosePlay issued server command: /sw report
--
[20:36:55] [pool-3-thread-8/WARN]: [SkyWars] Plugin SkyWars v2.2.2 generated an exception while executing task 49
java.lang.NullPointerException: null
at java.net.URLEncoder.encode(URLEncoder.java:204) ~[?:1.8.0_181]
at net.daboross.bukkitdev.skywars.gist.GistReport.shortenURL(GistReport.java:223) ~[?:?]
at net.daboross.bukkitdev.skywars.gist.GistReport.reportReport(GistReport.java:156) ~[?:?]
at net.daboross.bukkitdev.skywars.commands.mainsubcommands.ReportCommand$GistReportRunnable.run(ReportCommand.java:75) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[craftbukkit-1.12.2.jar:git-Bukkit-68b4fb6]
at  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)  [craftbukkit-1.12.2.jar:git-Bukkit-68b4fb6]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
